run:
	xelatex mimic-omop.tex
	bibtex mimic-omop.aux
	xelatex mimic-omop.tex
	xelatex mimic-omop.tex

run_adrien:
	/usr/local/texlive/2018/bin/x86_64-darwin/xelatex mimic-omop.tex
	/usr/local/texlive/2018/bin/x86_64-darwin/bibtex mimic-omop.aux
	/usr/local/texlive/2018/bin/x86_64-darwin/xelatex mimic-omop.tex
	/usr/local/texlive/2018/bin/x86_64-darwin/xelatex mimic-omop.tex
